### ISSUE TITLE
Specify Load Balancer in Resource Groups other than default

### ISSUE THREAD

**Issue by leochu** [cloudfoundry/bosh-azure-cpi-release#328]
Support load balancers in resource groups other than the default resource group.

https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/33f3e636244ec4ae937596a8f17b38e0bd1cc002/src/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb#L1199-L1202

**Comment by gossion** [comment]
It is doable to add `resource_group_name` as a parameter to `get_load_balancer_by_name`, now the question now is where to place this `resource_group_name`.

A suggestion is to reuse `resource_group_name` specified in `cloud-properties` of `networks` since load balancer is part of network resource, so load balancer, virutal network, security group are put in the same resource group. Config example as below. Azure CPI will search load balancer in this resource group `RG1' and bind VM to it, if it can't be found, CPI will then search it in the default resource group.

```yaml
    networks:
    - name: private
      type: manual
      subnets:
      - range: 10.0.0.0/24
        gateway: 10.0.0.1
        dns: [168.63.129.16]
        cloud_properties:
          resource_group_name: RG1   ### Reuse this resource group. Load balancer & security group & virtual network will be put in this resource group `RG1' together
          virtual_network_name: boshvnet-crp
          subnet_name: Bosh

    resource_pools:
    - name: resource_with_lb
      ...
      network: private
      cloud_properties:
        load_balancer: cf-lb
        instance_type: Standard_D1
```

@leochu, are you okay with this design?
