### ISSUE TITLE
Updating instance gives PrivateIPAddressIsAllocated in v35.5.0

### ISSUE THREAD

**Issue by ansd** [cloudfoundry/bosh-azure-cpi-release#603]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 35.5.0
BOSH     Version: 268.3.0
CF       Version: -
Diego    Version: -

### Stemcell
Version: bosh-azure-hyperv-ubuntu-trusty-go_agent  3586.54
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

### Issue Details

When redeploying an existing deployment, forcing the CPI to recreate the instance by changing the vm_type, we get the error below.
With version 35.4.0 the workflow described below succeeds.

### Logs (*Please redact all sensitive information in your logs*)
Error message: {
  "error": {
    "code": "PrivateIPAddressIsAllocated",
    "message": "IP configuration /subscriptions/<...>/resourceGroups/rg-azure-staging/providers/Microsoft.Network/networkInterfaces/<...>/ipConfigurations/ipconfig0 is using the private IP address 10.0.0.1 which is already allocated to resource /subscriptions/<...>/resourceGroups/rg-azure-staging/providers/Microsoft.Network/networkInterfaces/<...>.",
    "details": []
  }
}>

### Repro steps (*if necessary, delete otherwise*)
* deploy [dummy](https://github.com/pivotal-cf-experimental/dummy-boshrelease)

```
---
name: dummy

releases:
- name: dummy
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: dummy
  instances: 1
  vm_type: vm_2cpu_8gb
  stemcell: ubuntu
  networks:
  - name: default
    static_ips:
      - 10.0.0.1
  azs:
  - z1
  jobs:
  - name: dummy
    release: dummy

update:
  canaries: 1
  max_in_flight: 6
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
```

* change vm_type and redeploy

```
---
name: dummy

releases:
- name: dummy
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: dummy
  instances: 1
  vm_type: vm_4cpu_8gb
  stemcell: ubuntu
  networks:
  - name: default
    static_ips:
      - 10.0.0.1
  azs:
  - z1
  jobs:
  - name: dummy
    release: dummy

update:
  canaries: 1
  max_in_flight: 6
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
```
