### ISSUE TITLE
Azure ephemeral OS/temp disk

### ISSUE THREAD

**Issue by ahelal** [cloudfoundry/bosh-azure-cpi-release#671]
Hello Folks,

Azure offers ephemeral OS and temp disks for Azure VMs https://learn.microsoft.com/en-us/azure/virtual-machines/ephemeral-os-disks this can help a lot with *TCO* and *performance* for a various CF components. 

I created a small PoC and I want to discuses some design decision before doing a PR.

In order to configure this feature the cloud config can look like this.

```yaml
vm_types:
-  name: Standard_DS1_v2_e2
    cloud_properties:
        instance_type: Standard_DS1_v2
        ephemeral_disk:
          use_root_disk: true
          size: 6144
        root_disk:
          size: 30720
          use_instance_local_storage: true
```

I would add a new flag  `use_instance_local_storage` and if set to *true*, it will attempt to use Azure ephemeral disk.

As for root_disk `size` if left empty will use all possible disk space as a SSD for that vm type. if not will fallback on default behaviour.  
In case of error it will boil up normally to user

The implantation is quite simple we would need to append `diffDiskSettings` to the REST API

Thank you,
@MSSedusch @happytobi  @ahelal
